openapi: 3.0.0
info:
  title: Food Order API
  version: 1.0.0
  description: API for managing orders and order items
paths:
  /api/orders:
    post:
      summary: Create a new order
      tags:
        - Orders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_id:
                  type: integer
                order_date:
                  type: string
                  format: date
                total:
                  type: number
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      product_id:
                        type: integer
                      quantity:
                        type: integer
                      price:
                        type: number
      responses:
        '201':
          description: Order created
        '400':
          description: Validation error
        '500':
          description: Internal server error
